In [14]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [15]:
data = pd.read_csv("/content/Transformed_Housing_Data.csv")
data.head()

           ID  Sale Price  ...  Ever Renovated  Years Since Renovation
0  7129300520    221900.0  ...              No                       0
1  6414100192    538000.0  ...             Yes                      26
2  5631500400    180000.0  ...              No                       0
3  2487200875    604000.0  ...              No                       0
4  1954400510    510000.0  ...              No                       0

[5 rows x 21 columns]

In [16]:
from statsmodels.formula.api import ols
import statsmodels.api as sm

In [17]:
data = data.rename(columns= {'Sale Price' : 'Sale_Price'})
data = data.rename(columns= {'Condition of the House' : 'Condition_of_the_House'})
data = data.rename(columns= {'Waterfront View' : 'Waterfront_View'})
data = data.rename(columns= {'Ever Renovated' : 'Ever_Renovated'})

In [18]:
data.head()

           ID  Sale_Price  ...  Ever_Renovated  Years Since Renovation
0  7129300520    221900.0  ...              No                       0
1  6414100192    538000.0  ...             Yes                      26
2  5631500400    180000.0  ...              No                       0
3  2487200875    604000.0  ...              No                       0
4  1954400510    510000.0  ...              No                       0

[5 rows x 21 columns]

In [19]:
#ANOVA
#Checks whether the variable has an impact on the target variable


mod = ols('Sale_Price ~ Condition_of_the_House', data = data).fit()
sm.stats.anova_lm(mod, typ = 2)

                              sum_sq       df         F        PR(>F)
Condition_of_the_House  1.441831e+13      4.0  58.25563  5.447605e-49
Residual                1.336752e+15  21604.0       NaN           NaN

In [20]:
#Create Dummy Variables

data = pd.get_dummies(data, columns= ['Condition_of_the_House'], drop_first= True)

In [21]:
data = pd.get_dummies(data, columns= ['Waterfront_View', 'Ever_Renovated'], drop_first= True)

In [23]:
data.head()

           ID  Sale_Price  ...  Waterfront_View_Yes  Ever_Renovated_Yes
0  7129300520    221900.0  ...                    0                   0
1  6414100192    538000.0  ...                    0                   1
2  5631500400    180000.0  ...                    0                   0
3  2487200875    604000.0  ...                    0                   0
4  1954400510    510000.0  ...                    0                   0

[5 rows x 24 columns]

# **`BINNING`**

In [25]:
zip = data.groupby('Zipcode').agg({'Sale_Price': 'mean'}).sort_values('Sale_Price', ascending = True)
zip.head()

            Sale_Price
Zipcode
98002.0  234284.035176
98168.0  240328.371747
98032.0  251296.240000
98001.0  280804.690608
98148.0  284908.596491

In [26]:
zip['Zip_Group'] = pd.cut(zip['Sale_Price'], bins = 10,
                          labels = ['Zip_0',
                                    'Zip_1',
                                    'Zip_2',
                                    'Zip_3',
                                    'Zip_4',
                                    'Zip_5',
                                    'Zip_6',
                                    'Zip_7',
                                    'Zip_8',
                                    'Zip_9'], include_lowest = True)

In [27]:
zip = zip.drop(columns = 'Sale_Price')

In [28]:
data = pd.merge(data, zip, left_on= 'Zipcode', how = 'left', right_index= True)

In [29]:
data = data.drop(columns = 'Zipcode')

In [30]:
data = pd.get_dummies(data, columns= ['Zip_Group'], drop_first= True)

In [31]:
data.head()

           ID  Sale_Price  ...  Zip_Group_Zip_8  Zip_Group_Zip_9
0  7129300520    221900.0  ...                0                0
1  6414100192    538000.0  ...                0                0
2  5631500400    180000.0  ...                0                0
3  2487200875    604000.0  ...                0                0
4  1954400510    510000.0  ...                0                0

[5 rows x 32 columns]